# Generated by Django 4.1.5 on 2023-01-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='employment_status',
            field=models.CharField(choices=[('Employeed', 'Employeed'), ('Looking for Job', 'Looking for Job'), ('Doing Internship', 'Doing Internship')], max_length=30, null=True),
        ),
    ]
